# Generated by Django 3.1.2 on 2021-03-21 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, max_length=100)),
                ('contact_no', models.TextField(blank=True, max_length=20)),
                ('site', models.CharField(choices=[('RGPI Pasig', 'RGPI Pasig'), ('RGPI Calamba', 'RGPI Calamba'), ('RGPI Silang', 'RGPI Silang'), ('RGPI Sta. Cruz', 'RGPI Sta. Cruz'), ('RGPI Sta. Lipa', 'RGPI Sta. Lipa'), ('RGPI Sta. Balayan', 'RGPI Sta. Balayan'), ('RGPI Sta. Antipolo', 'RGPI Sta. Antipolo')], default='-------------', max_length=30)),
                ('department', models.CharField(choices=[('IT', (('Reports & Data Analyst', 'Reports & Data Analyst'), ('End User Support', 'End User Support'), ('IT Manager', 'IT Manager'), ('IT Supervisor', 'IT Supervisor'))), ('Sales', (('Sales Supervisor', 'Sales Supervisor'), ('Operational Manager', 'Operational Manager'), ('Seller', 'Seller'), ('Key Accounts Executive', 'Key Accounts Executive'), ('PSG', 'PSG'))), ('HR', (('HR Manager', 'HR Manager'), ('HR Supervisor', 'HR Supervisor'), ('HR Staff', 'HR Staff')))], default='-------------', max_length=30)),
                ('image', models.ImageField(blank=True, default='media/default.jpg', null=True, upload_to='profile_pics/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
